---
driver:
  name: vagrant
  provider: virtualbox
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.3.0"

platforms:
- name: centos6-vagrant
  driver:
    box: coremedia/base
    box_url: 'http://boxes.coremedia.com/vagrant/coremedia-centos6-base-box.json'
    #network:
    #- ['private_network',{ ip: '192.168.252.100' }]

- name: centos7-vagrant
  driver:
    box: coremedia/base7
    box_url: 'http://boxes.coremedia.com/vagrant/coremedia-centos7-base-box.json'

suites:
- name: pcp
  run_list:
    - recipe[pcp::default]
    - recipe[pcp::vector]
  attributes:
    pcp:
      nginx:
        fqdn: pcp-centos6-vagrant
        disable_default_site: true
      yum:
        baseurl: http://mirror.coremedia.vm/coremedia-pcp/el/6/$basearch
    dev_mode: true

- name: vector_only
  runlist:
    - recipe[pcp::vector]]
